[2025-07-02T08:42:22.880] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
[2025-07-02T08:42:22.886] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
[2025-07-02T08:42:22.886] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
[2025-07-02T08:42:23.006] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 9.0.2. Build: 9
[2025-07-02T08:42:35.925] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
[2025-07-02T08:42:35.929] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
[2025-07-02T08:42:35.929] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
[2025-07-02T08:42:36.031] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 9.0.2. Build: 9
[2025-07-02T08:46:31.654] [ERROR] [localhost] [192.168.65.1new.docx1751445991255] [uid-1] nodeJS - postData error: url = http://localhost:8080/example/track?filename=new.docx&useraddress=192.168.65.1;data = {"key":"192.168.65.1new.docx1751445991255","status":1,"users":["uid-1"],"actions":[{"type":1,"userid":"uid-1"}],"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxOTIuMTY4LjY1LjFuZXcuZG9jeDE3NTE0NDU5OTEyNTUiLCJzdGF0dXMiOjEsInVzZXJzIjpbInVpZC0xIl0sImFjdGlvbnMiOlt7InR5cGUiOjEsInVzZXJpZCI6InVpZC0xIn1dLCJpYXQiOjE3NTE0NDU5OTEsImV4cCI6MTc1MTQ0NjI5MX0.Fgq9oDOS1x2qdEo32-9YzIfTJZVaW8w97ahiABq7nqw"} Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.postRequestPromise (/snapshot/server/Common/sources/utils.js)
    at async sendServerRequest (/snapshot/server/DocService/sources/DocsCoServer.js)
    at async sendStatusDocument (/snapshot/server/DocService/sources/DocsCoServer.js)
[2025-07-02T08:46:36.167] [ERROR] [localhost] [192.168.65.1new.docx1751445991255] [uid-11] nodeJS - postData error: url = http://localhost:8080/example/track?filename=new.docx&useraddress=192.168.65.1;data = {"key":"192.168.65.1new.docx1751445991255","status":4,"actions":[{"type":0,"userid":"uid-1"}],"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxOTIuMTY4LjY1LjFuZXcuZG9jeDE3NTE0NDU5OTEyNTUiLCJzdGF0dXMiOjQsImFjdGlvbnMiOlt7InR5cGUiOjAsInVzZXJpZCI6InVpZC0xIn1dLCJpYXQiOjE3NTE0NDU5OTYsImV4cCI6MTc1MTQ0NjI5Nn0.hs5BPCs7Ykk0p3eNMwGCtE98WiYlvRHSuAEUsmIXlNQ"} Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.postRequestPromise (/snapshot/server/Common/sources/utils.js)
    at async sendServerRequest (/snapshot/server/DocService/sources/DocsCoServer.js)
    at async sendStatusDocument (/snapshot/server/DocService/sources/DocsCoServer.js)
[2025-07-02T08:46:39.536] [ERROR] [localhost] [192.168.65.1new__1_.docx1751445999337] [uid-1] nodeJS - postData error: url = http://localhost:8080/example/track?filename=new%20(1).docx&useraddress=192.168.65.1;data = {"key":"192.168.65.1new__1_.docx1751445999337","status":1,"users":["uid-1"],"actions":[{"type":1,"userid":"uid-1"}],"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxOTIuMTY4LjY1LjFuZXdfXzFfLmRvY3gxNzUxNDQ1OTk5MzM3Iiwic3RhdHVzIjoxLCJ1c2VycyI6WyJ1aWQtMSJdLCJhY3Rpb25zIjpbeyJ0eXBlIjoxLCJ1c2VyaWQiOiJ1aWQtMSJ9XSwiaWF0IjoxNzUxNDQ1OTk5LCJleHAiOjE3NTE0NDYyOTl9.R0ZfZIMly4K-OJw1flBRQsF9xem0AmI6xSs42eUW7Mk"} Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.postRequestPromise (/snapshot/server/Common/sources/utils.js)
    at async sendServerRequest (/snapshot/server/DocService/sources/DocsCoServer.js)
    at async sendStatusDocument (/snapshot/server/DocService/sources/DocsCoServer.js)
[2025-07-02T08:46:44.635] [ERROR] [localhost] [192.168.65.1new__1_.docx1751445999337] [uid-11] nodeJS - postData error: url = http://localhost:8080/example/track?filename=new%20(1).docx&useraddress=192.168.65.1;data = {"key":"192.168.65.1new__1_.docx1751445999337","status":4,"actions":[{"type":0,"userid":"uid-1"}],"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxOTIuMTY4LjY1LjFuZXdfXzFfLmRvY3gxNzUxNDQ1OTk5MzM3Iiwic3RhdHVzIjo0LCJhY3Rpb25zIjpbeyJ0eXBlIjowLCJ1c2VyaWQiOiJ1aWQtMSJ9XSwiaWF0IjoxNzUxNDQ2MDA0LCJleHAiOjE3NTE0NDYzMDR9.Xwe1VH656PUwyVm-JMpEXTprCIUZt3wMAMa_byJ08jE"} Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.postRequestPromise (/snapshot/server/Common/sources/utils.js)
    at async sendServerRequest (/snapshot/server/DocService/sources/DocsCoServer.js)
    at async sendStatusDocument (/snapshot/server/DocService/sources/DocsCoServer.js)
[2025-07-02T08:46:55.423] [ERROR] [localhost] [192.168.65.1new__2_.docx1751446015220] [uid-1] nodeJS - postData error: url = http://localhost:8080/example/track?filename=new%20(2).docx&useraddress=192.168.65.1;data = {"key":"192.168.65.1new__2_.docx1751446015220","status":1,"users":["uid-1"],"actions":[{"type":1,"userid":"uid-1"}],"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxOTIuMTY4LjY1LjFuZXdfXzJfLmRvY3gxNzUxNDQ2MDE1MjIwIiwic3RhdHVzIjoxLCJ1c2VycyI6WyJ1aWQtMSJdLCJhY3Rpb25zIjpbeyJ0eXBlIjoxLCJ1c2VyaWQiOiJ1aWQtMSJ9XSwiaWF0IjoxNzUxNDQ2MDE1LCJleHAiOjE3NTE0NDYzMTV9.V33DIRTwH2QQl2ayVXp6eOvoBlUsxqQuxxiEdx58UFc"} Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.postRequestPromise (/snapshot/server/Common/sources/utils.js)
    at async sendServerRequest (/snapshot/server/DocService/sources/DocsCoServer.js)
    at async sendStatusDocument (/snapshot/server/DocService/sources/DocsCoServer.js)
[2025-07-02T09:01:15.818] [ERROR] [localhost] [192.168.65.1new.xlsx1751446875408] [uid-1] nodeJS - postData error: url = http://localhost:8080/example/track?filename=new.xlsx&useraddress=192.168.65.1;data = {"key":"192.168.65.1new.xlsx1751446875408","status":1,"users":["uid-1"],"actions":[{"type":1,"userid":"uid-1"}],"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxOTIuMTY4LjY1LjFuZXcueGxzeDE3NTE0NDY4NzU0MDgiLCJzdGF0dXMiOjEsInVzZXJzIjpbInVpZC0xIl0sImFjdGlvbnMiOlt7InR5cGUiOjEsInVzZXJpZCI6InVpZC0xIn1dLCJpYXQiOjE3NTE0NDY4NzUsImV4cCI6MTc1MTQ0NzE3NX0.Y-xXz8k8_bwMDMt3q88rBULAKSeDlVfD5pnbNII4gPc"} Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.postRequestPromise (/snapshot/server/Common/sources/utils.js)
    at async sendServerRequest (/snapshot/server/DocService/sources/DocsCoServer.js)
    at async sendStatusDocument (/snapshot/server/DocService/sources/DocsCoServer.js)
[2025-07-02T09:01:21.909] [ERROR] [localhost] [192.168.65.1new.xlsx1751446875408] [uid-11] nodeJS - postData error: url = http://localhost:8080/example/track?filename=new.xlsx&useraddress=192.168.65.1;data = {"key":"192.168.65.1new.xlsx1751446875408","status":4,"actions":[{"type":0,"userid":"uid-1"}],"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxOTIuMTY4LjY1LjFuZXcueGxzeDE3NTE0NDY4NzU0MDgiLCJzdGF0dXMiOjQsImFjdGlvbnMiOlt7InR5cGUiOjAsInVzZXJpZCI6InVpZC0xIn1dLCJpYXQiOjE3NTE0NDY4ODEsImV4cCI6MTc1MTQ0NzE4MX0.w5dRfYnZqbpmYsRgobINKJ5xNrXSaLVlGtJAcUq8kO8"} Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.postRequestPromise (/snapshot/server/Common/sources/utils.js)
    at async sendServerRequest (/snapshot/server/DocService/sources/DocsCoServer.js)
    at async sendStatusDocument (/snapshot/server/DocService/sources/DocsCoServer.js)
[2025-07-02T09:01:24.420] [ERROR] [localhost] [192.168.65.1new.pptx1751446884075] [uid-1] nodeJS - postData error: url = http://localhost:8080/example/track?filename=new.pptx&useraddress=192.168.65.1;data = {"key":"192.168.65.1new.pptx1751446884075","status":1,"users":["uid-1"],"actions":[{"type":1,"userid":"uid-1"}],"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxOTIuMTY4LjY1LjFuZXcucHB0eDE3NTE0NDY4ODQwNzUiLCJzdGF0dXMiOjEsInVzZXJzIjpbInVpZC0xIl0sImFjdGlvbnMiOlt7InR5cGUiOjEsInVzZXJpZCI6InVpZC0xIn1dLCJpYXQiOjE3NTE0NDY4ODQsImV4cCI6MTc1MTQ0NzE4NH0.U7HKO6ZLDM70FEH1R-OZudLP-PC24nmaMP9VRXWMHiw"} Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.postRequestPromise (/snapshot/server/Common/sources/utils.js)
    at async sendServerRequest (/snapshot/server/DocService/sources/DocsCoServer.js)
    at async sendStatusDocument (/snapshot/server/DocService/sources/DocsCoServer.js)
[2025-07-02T09:01:43.401] [ERROR] [localhost] [192.168.65.1new.pptx1751446884075] [uid-11] nodeJS - postData error: url = http://localhost:8080/example/track?filename=new.pptx&useraddress=192.168.65.1;data = {"key":"192.168.65.1new.pptx1751446884075","status":4,"actions":[{"type":0,"userid":"uid-1"}],"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxOTIuMTY4LjY1LjFuZXcucHB0eDE3NTE0NDY4ODQwNzUiLCJzdGF0dXMiOjQsImFjdGlvbnMiOlt7InR5cGUiOjAsInVzZXJpZCI6InVpZC0xIn1dLCJpYXQiOjE3NTE0NDY5MDMsImV4cCI6MTc1MTQ0NzIwM30.-wjjVazd9-MQc16JKV87KgkDVzaZYUVm6vMKuEURtyw"} Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.postRequestPromise (/snapshot/server/Common/sources/utils.js)
    at async sendServerRequest (/snapshot/server/DocService/sources/DocsCoServer.js)
    at async sendStatusDocument (/snapshot/server/DocService/sources/DocsCoServer.js)
[2025-07-02T09:01:49.075] [ERROR] [localhost] [192.168.65.1new.docx1751446908787] [uid-1] nodeJS - postData error: url = http://localhost:8080/example/track?filename=new.docx&useraddress=192.168.65.1;data = {"key":"192.168.65.1new.docx1751446908787","status":1,"users":["uid-1"],"actions":[{"type":1,"userid":"uid-1"}],"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxOTIuMTY4LjY1LjFuZXcuZG9jeDE3NTE0NDY5MDg3ODciLCJzdGF0dXMiOjEsInVzZXJzIjpbInVpZC0xIl0sImFjdGlvbnMiOlt7InR5cGUiOjEsInVzZXJpZCI6InVpZC0xIn1dLCJpYXQiOjE3NTE0NDY5MDksImV4cCI6MTc1MTQ0NzIwOX0.7oKPElMwfvTZhf3qgF0AAyaaVjvpOPT_G_1JeuidnnM"} Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.postRequestPromise (/snapshot/server/Common/sources/utils.js)
    at async sendServerRequest (/snapshot/server/DocService/sources/DocsCoServer.js)
    at async sendStatusDocument (/snapshot/server/DocService/sources/DocsCoServer.js)
[2025-07-02T09:01:56.646] [ERROR] [localhost] [192.168.65.1new.docx1751446908787] [uid-11] nodeJS - postData error: url = http://localhost:8080/example/track?filename=new.docx&useraddress=192.168.65.1;data = {"key":"192.168.65.1new.docx1751446908787","status":4,"actions":[{"type":0,"userid":"uid-1"}],"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxOTIuMTY4LjY1LjFuZXcuZG9jeDE3NTE0NDY5MDg3ODciLCJzdGF0dXMiOjQsImFjdGlvbnMiOlt7InR5cGUiOjAsInVzZXJpZCI6InVpZC0xIn1dLCJpYXQiOjE3NTE0NDY5MTYsImV4cCI6MTc1MTQ0NzIxNn0.RyrKR3AjOaGnYC2YElo-cGc2UYMP3Cja9jkK6sssYSA"} Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.postRequestPromise (/snapshot/server/Common/sources/utils.js)
    at async sendServerRequest (/snapshot/server/DocService/sources/DocsCoServer.js)
    at async sendStatusDocument (/snapshot/server/DocService/sources/DocsCoServer.js)
